
name: Terraform Deployment

on:
  push:
    branches:
      - main  # This will trigger the workflow on pushing to the main branc

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0  # Specify the Terraform version you need

    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Change directory to the folder containing terraform files
      run: cd infra/compute/

    - name: Terraform Init
      run: terraform init
      working-directory: infra/compute

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: infra/compute


    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: infra/compute

  #  - name: Run Destroy Script
 #     run: bash destroy.sh

